### PR TITLE
CAS-106: Add Endpoint for query community users by userType

### PR DESCRIPTION
**Pull request by jbluks**
**Ticket:** [CAS-106](https://linear.app/dappercollectives/issue/CAS-106/get-community-users-by-type-api-endpoint)

**Description:**

- Fixes test for `/communities/[communityId]/users` endpoint
- Removes unused code block in `TestCreateCommunityUsers`
- Adds endpoint `/communities/[communityId]/users/type/[userType]`
- Adds tests for above endpoint

### CODE REVIEW

**Review by rvmelkonian — COMMENTED** [review]
I'm getting a failing test on `TestCommunityAdminRoles ` with a pgx scanny error output `scany: rows final error: ERROR: invalid input value for enum user_types: "invalidType" (SQLSTATE 22P02)` 

My guess is that you've have updated this enum manually on your DB? If yes you'll need to create a new migrations file so that when we run `make testmigrateup` / down, we get the new SQL table data :)

**Comment by jacksonConrad** [comment]
similar to Richard i'm also seeing the `TestCommunityAdminRoles` test failing.  I think the `scany` log statement is expected but if you could remove unnecessary log statements that would be great :)

**Comment by jacksonConrad** [comment]
otherwise, looks great!

**Comment by jbluks** [comment]
Tests Fixed and cleaned up to remove unnecessary noise.

**Comment by rvmelkonian** [comment]
Looks good!

**Review by jacksonConrad — APPROVED** [review]
lgtm!

**Pull request merged**
