### PR TITLE
CAS-502: Remove unused cadence scripts and add tests directory

### PR DESCRIPTION
**Pull request by jbluks**
- Old Cadence scripts removed
- Tests moved to a `tests` directory to put them all in one place, and separate them out from the source code.

### CODE REVIEW

**Comment by jacksonConrad** [comment]
The tests are failing for me on this branch with the following error:

```
--- FAIL: TestCreateCommunity (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4994a9c]
```

i'm seeing this in the stack trace, which is odd:
```
github.com/DapperCollectives/CAST/backend/main/server.(*App).createCommunity(0x0?, {0x564f5f0, 0xc0008cba80}, 0xc0005bcd00)
        /Users/jacksonfoley/Code/CAST/backend/main/server/controllers.go:362 +0x19c
net/http.HandlerFunc.ServeHTTP(0x50a9020?, {0x564f5f0?, 0xc0008cba80?}, 0x11?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/DapperCollectives/CAST/backend/main/middleware.UseCors.func1.1({0x564f5f0, 0xc0008cba80}, 0xc0005bcd00)
        /Users/jacksonfoley/Code/CAST/backend/main/middleware/cors.go:23 +0x283
```

I'm running `make test` from the `CAST/backend` directory.  Are tests passing for you @jbluks ?

**Comment by jacksonConrad** [comment]
ahh looks like `*payload.Proposal_threshold` may be a null pointer on `controllers.go:362` -- are you able to reproduce?

`propThreshold, err := strconv.ParseFloat(*payload.Proposal_threshold, 64)`

**Comment by jbluks** [comment]
Yea, that error did come up - but, it exists on main as well, so it is not related to these specific changes. I will dig deeper and see if I can resolve it.

**Comment by jbluks** [comment]
@jacksonConrad Fixed failing test. Issue was nil value for proposal threshold.

**Comment by tuffon** [comment]
I added a check here for nil pointer ref in the validation as well.  Wanted to follow up by asking if the unused cadence scripts could be useful in an examples directory or as a reference for script developers?

**Comment by jacksonConrad** [comment]
> I added a check here for nil pointer ref in the validation as well. Wanted to follow up by asking if the unused cadence scripts could be useful in an examples directory or as a reference for script developers?

@tuffon nah, those scripts were largely experimental and unrelated to CAST in its current form.

**Comment by jbluks** [comment]
@tuffon I'll merge your changes in to fix the broken tests in this branch.

**Review by jacksonConrad — APPROVED** [review]

**Pull request merged**
